import { normalizeCatch } from "./catches";

export const DEMO_CATCHES = [
  {
    id: "demo-1",
    angler: "Robin",
    species: "Gädda",
    length: 108,
    weight: 9.7,
    date: "2026-05-12",
    location: "Mälaren, sydväst",
    method: "Jerkbait",
    weather: "Mulet, lätt sydvind",
    lure: "Firetiger 14 cm",
    note: "Högg tungt direkt efter paus i vändningen.",
    photoUrl: "/ee8f50881dabb92dbbc519f6c5eab94f.webp",
    mood: "Låst in",
    tags: ["PB", "grunt", "kväll"],
    released: true,
    tripName: "Kvällspass bland vassarna"
  },
  {
    id: "demo-2",
    angler: "Cathlin",
    species: "Abborre",
    length: 43,
    weight: 1.08,
    date: "2026-04-28",
    location: "Skärgården, brant kant",
    method: "Dropshot",
    weather: "Klart, kylig morgon",
    lure: "Mörk shad 8 cm",
    note: "Stenhårt hugg direkt på första stoppen.",
    photoUrl: "/ee8f50881dabb92dbbc519f6c5eab94f.webp",
    mood: "Skärpt",
    tags: ["morgon", "kant"],
    released: true,
    tripName: "Morgon på djupkanten"
  },
  {
    id: "demo-3",
    angler: "Båda",
    species: "Gös",
    length: 71,
    weight: 3.9,
    date: "2026-03-18",
    location: "Hjälmaren, djuphåla",
    method: "Vertikaljigg",
    weather: "Dis, nästan vindstilla",
    lure: "Pearl jigg 12 cm",
    note: "Tog på långsam presentation under båten.",
    photoUrl: "/crpredators.png",
    mood: "Metodisk",
    tags: ["team", "vertikal"],
    released: true,
    tripName: "Sakta drift över djupet"
  },
  {
    id: "demo-4",
    angler: "Cathlin",
    species: "Öring",
    length: 58,
    weight: 2.6,
    date: "2026-02-23",
    location: "Kustudden norr",
    method: "Genomlöpande drag",
    weather: "Klar luft, krispigt",
    lure: "Silver/orange 24 g",
    note: "Kom efter lång kastserie när ytan låg nästan blank.",
    photoUrl: "/ee8f50881dabb92dbbc519f6c5eab94f.webp",
    mood: "Lugn",
    tags: ["kust"],
    released: true,
    tripName: "Vinterluft vid udden"
  },
  {
    id: "demo-5",
    angler: "Robin",
    species: "Gädda",
    length: 91,
    weight: 6.2,
    date: "2026-01-14",
    location: "Insjövik, norra udden",
    method: "Spinnfiske",
    weather: "Låg sol, kallt vatten",
    lure: "Softbait 18 cm",
    note: "Fiskade långsamt över döende gräs.",
    photoUrl: "/crpredators.png",
    mood: "Tålmodig",
    tags: ["vinter", "gräs"],
    released: false,
    tripName: "Seg vinterdag"
  },
  {
    id: "demo-6",
    angler: "Båda",
    species: "Abborre",
    length: 39,
    weight: 0.86,
    date: "2026-05-02",
    location: "Mälaren, stenbank",
    method: "Ned-riggad jigg",
    weather: "Solglimtar, ryckig vind",
    lure: "Motor oil 7 cm",
    note: "Hittade stimmet sent men det räddade hela turen.",
    photoUrl: "/ee8f50881dabb92dbbc519f6c5eab94f.webp",
    mood: "Lättad",
    tags: ["stim", "sen räddning"],
    released: true,
    tripName: "Lunchpass på stenbanken"
  }
].map(normalizeCatch);
